name: Tests
on:
    push:
        branches:
            - master

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: yarn install
            - name: Run Tests
              env:
                  CI: true
              run: yarn test
            - name: Upload coverage
              run: yarn coverage:upload --token="${{ secrets.CODECOV_TOKEN }}"
